### ISSUE TITLE
Check problematic links

### ISSUE THREAD

**Issue by uyar** [cinemagoer/website#3]
Some links on the SF site aren't working. Some official platform packages (like Mac OS X), and also some links to projects on the ecosystem page. These need to be reviewed and either updated with current links, or marked as dead (or removed altogether).

**Comment by alberanid** [comment]
Honestly, I'd prefer to scrap all the entries in Ecosystem except the papers.

The link to software and services are too getting old and it's too difficult to keep track of new projects.

Let me know if there are problems with that.

**Comment by uyar** [comment]
I agree, even the top entries on the page are outdated.

**Comment by alberanid** [comment]
ok, now I'm okay with the content.

**Comment by uyar** [comment]
Great. I don't have anything left either related to content. The contrast issue can be dealt with later. I guess the site is ready.

**Comment by uyar** [comment]
Have you checked the ecosystem page on the current site? I haven't reviewed the entries below fobox. There might be more content to migrate there.

**Comment by alberanid** [comment]
I did and I think there is nothing else worth to be saved. As always if you have anything to add, just commit+push it.

As soon as possible I will:
* change the web page on the sourceforge site to point to https://imdbpy.github.io/
* do a search and replace of the old site in the source code of IMDbPY

anything else that must be done?

Are https://github.com/imdbpy/website/network/alerts serious issues?

**Comment by uyar** [comment]
No, nothing else comes to mind. And I don't have any more content to add at the moment.

I guess the security alerts would be important if this were an application that used those. Here they are used only during the build process, therefore I don't think that they matter. I'll try to find ways around them but I'm very incompetent when it comes to JS. What we need is:

- Run sass to generate the CSS based on Bulma.
- Run uncss to get rid of the unused CSS rules. This is important because it cuts the CSS file from 130K down to 9K.
- Minify the CSS file.

The last two steps are currently by grunt (I'm just copy pasting what I find on the Internet, I don't think it makes sense to do it this way.) Some of these could be done via lektor plugins or through the command line.

**Comment by alberanid** [comment]
oh, I see. It make sense, we could probably just ignore them. I've already updated the code and the sourceforge account; I've probably missed something, but I'll double check in the next days.

**Comment by uyar** [comment]
The GitHub repository description still points to sf.

**Comment by alberanid** [comment]
fixed, thanks.
